# Generated by Django 3.0.5 on 2020-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.IntegerField()),
                ('comment_owner', models.CharField(max_length=20)),
                ('num', models.IntegerField()),
                ('num_sub', models.IntegerField()),
                ('make_date', models.DateField(auto_now=True)),
                ('comment_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='post_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=20)),
                ('make_date', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(default=0)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('pw', models.CharField(max_length=20)),
                ('friend', models.TextField()),
            ],
        ),
    ]
